font_family GeistMono Nerd Font Mono
font_size 12
disable_ligatures no
enable_audio_bell no
background #030c1a
background_opacity 0.50
background_blur 1
sync_to_monitor no
confirm_os_window_close 0
notify_on_cmd_finish unfocused
