font_family GeistMono Nerd Font Mono
font_size 12
disable_ligatures no
enable_audio_bell no
background #030c1a
background_opacity 0.50
background_blur 1
sync_to_monitor no
confirm_os_window_close 0
notify_on_cmd_finish unfocused
# Enable cursor trail (any value > 0 enables it)
cursor_trail 3

# Control how fast the trail fades (min_decay max_decay in seconds)
cursor_trail_decay 0.05 0.15 
#second val must be > than first

# Optional: set a custom trail color (independent of cursor color)
#cursor_trail_color #pink  # or any hex color
