$primary = rgb(acc7ff)
$on_primary = rgb(0f2f60)
$primary_container = rgb(2a4678)
$on_primary_container = rgb(d7e2ff)
$secondary = rgb(bec6dc)
$on_secondary = rgb(283041)
$secondary_container = rgb(3f4759)
$on_secondary_container = rgb(dae2f9)
$tertiary = rgb(debcdf)
$on_tertiary = rgb(402844)
$tertiary_container = rgb(583e5b)
$on_tertiary_container = rgb(fbd7fc)
$surface = rgb(111318)
$on_surface = rgb(e2e2e9)
$surface_variant = rgb(44474f)
$on_surface_variant = rgb(c4c6d0)
