$primary = rgb(feb876)
$on_primary = rgb(4b2800)
$primary_container = rgb(6a3b02)
$on_primary_container = rgb(ffdcbf)
$secondary = rgb(e2c0a4)
$on_secondary = rgb(412c18)
$secondary_container = rgb(59422d)
$on_secondary_container = rgb(ffdcbf)
$tertiary = rgb(c1cc99)
$on_tertiary = rgb(2c340f)
$tertiary_container = rgb(424a23)
$on_tertiary_container = rgb(dde8b3)
$surface = rgb(19120c)
$on_surface = rgb(efe0d5)
$surface_variant = rgb(51443a)
$on_surface_variant = rgb(d5c3b6)
