$primary = rgb(91cef4)
$on_primary = rgb(00344b)
$primary_container = rgb(004c6a)
$on_primary_container = rgb(c5e7ff)
$secondary = rgb(b6c9d8)
$on_secondary = rgb(20333e)
$secondary_container = rgb(374955)
$on_secondary_container = rgb(d2e5f4)
$tertiary = rgb(cbc1e9)
$on_tertiary = rgb(332c4c)
$tertiary_container = rgb(494263)
$on_tertiary_container = rgb(e7deff)
$surface = rgb(0f1417)
$on_surface = rgb(dfe3e7)
$surface_variant = rgb(41484d)
$on_surface_variant = rgb(c1c7ce)
