-- Generated by nwg-displays on 2026-06-06 at 19:01:51. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "2880x1800@48.0",
    position = "0x0",
    scale = 1.5,
    bitdepth = 10
})
