
#Workspace specific layouts
workspace = 1, layout:scrolling
workspace = 2, layout:dwindle
workspace = 3, layout:dwindle
workspace = 4, layout:dwindle
workspace = 5, layout:dwindle
workspace = 6, layout:dwindle
workspace = 7, layout:dwindle
workspace = 8, layout:dwindle
workspace = 9, layout:dwindle

workspace = special:minimized, gapsout:80, gapsin:20, bordersize:4, layoutopt:orientation:center
dwindle {
    # See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
    pseudotile = yes # master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = yes # you probably want this
}

master {
    # See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
    new_on_active = true
}

gestures {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more
    workspace_swipe_touch = on
}

# Example per-device config
# See https://wiki.hyprland.org/Configuring/Keywords/#executing for more
device:epic-mouse-v1 {
    # sensitivity = -o.5
}
# scrolling (hyprland 0.53) — matches your provided table ordering

scrolling {
  # fullscreen_on_one_column: bool. default: true
  # - when enabled, a single column on a workspace will always span the entire screen.
  # fullscreen_on_one_column = true

  # column_width: float. default: 0.5
  # - the default width of a column, [0.1 - 1.0].
  #column_width = 0.55
 column_width = 0.95

  # focus_fit_method: int. default: 0
  # - when a column is focused, what method should be used to bring it into view. 0 = center, 1 = fit
  focus_fit_method = 1

  # follow_focus: bool. default: true
  # - when a window is focused, should the layout move to bring it into view automatically
  follow_focus = true

  # follow_min_visible: float. default: 0.4
  # - when a window is focused, require that at least a given fraction of it is visible for focus to follow. hard input (e.g. binds, clicks) will always follow. [0.0 - 1.0]
  follow_min_visible = 1.0

  # explicit_column_widths: str. default: 0.333, 0.5, 0.667, 1.0
  # - a comma-separated list of preconfigured widths for colresize +conf/-conf
  explicit_column_widths = 0.334, 0.5, 0.667, 1.0

  # direction: str. default: "right"
  # - direction in which new windows appear and the layout scrolls. left/right/down/up
  direction = down
}
