# See https://wiki.hyprland.org/Configuring/Monitors/
#monitor=,preferred,auto,auto
#monitor=eDP-1, 2880x1800@120, 0x0, 1.50
#For apps
xwayland {
  force_zero_scaling = true
}
misc{
#variable frame rate
vrr= 2
}
monitorv2 {
    output = eDP-1
    mode = 2880x1800@120
    position = 0x0
    scale = 1.5

    bitdepth = 10
    cm = hdr

    sdrbrightness = 1.0
    sdrsaturation = 1.1
    sdr_min_luminance = 0.01
    sdr_max_luminance = 220
    max_avg_luminance = 400
    max_luminance = 617
}

render {
    cm_auto_hdr = 2
}
