# See https://wiki.hyprland.org/Configuring/Monitors/
#monitor=,preferred,auto,auto
monitor=eDP-1, 2880x1800@120, 0x0, 1.50
#For apps
xwayland {
  force_zero_scaling = true
}
misc{
#variable frame rate
vrr= 2
}
